import { describe, it, expect } from 'vitest';
import type { ReleaseReport } from '@tagline-sh/shared';
import {
    acknowledgementComment,
    defaultWorkflowYaml,
    errorComment,
    missingWorkflowComment,
    noChangesComment,
    noPermissionComment,
    reportComment,
} from '../../src/utils/comments.js';

const sampleReport: ReleaseReport = {
    repoOwner: 'acme',
    repoName: 'widget',
    baseBranch: 'main',
    lastTag: 'v1.4.2',
    lastTagDate: '2026-04-28T00:00:00Z',
    prs: [
        {
            number: 342,
            title: 'feat(api): OAuth2 PKCE support',
            url: 'https://github.com/acme/widget/pull/342',
            author: 'octocat',
            mergedAt: '2026-05-10T10:00:00Z',
            commits: [
                {
                    type: 'feat',
                    scope: 'api',
                    subject: 'OAuth2 PKCE support',
                    body: null,
                    isBreaking: false,
                    sha: 'a',
                },
            ],
            tickets: ['PROJ-1201'],
            suggestedBump: 'minor',
            bodyExcerpt: null,
        },
        {
            number: 341,
            title: 'fix: token refresh race',
            url: 'https://github.com/acme/widget/pull/341',
            author: 'octocat',
            mergedAt: '2026-05-11T10:00:00Z',
            commits: [
                {
                    type: 'fix',
                    scope: null,
                    subject: 'token refresh race',
                    body: null,
                    isBreaking: false,
                    sha: 'b',
                },
            ],
            tickets: ['PROJ-1199'],
            suggestedBump: 'patch',
            bodyExcerpt: null,
        },
        {
            number: 340,
            title: 'chore: upgrade to Node 22',
            url: 'https://github.com/acme/widget/pull/340',
            author: 'octobot',
            mergedAt: '2026-05-12T10:00:00Z',
            commits: [
                {
                    type: 'chore',
                    scope: null,
                    subject: 'upgrade to Node 22',
                    body: null,
                    isBreaking: false,
                    sha: 'c',
                },
            ],
            tickets: [],
            suggestedBump: 'none',
            bodyExcerpt: null,
        },
    ],
    suggestedBump: 'minor',
    suggestedVersion: '1.5.0',
    currentVersion: '1.4.2',
    reasoning: 'Two substantial new features (#342) qualify this as a minor release.',
    changelogPreview:
        '## [1.5.0] - 2026-05-18\n\n### Added\n\n- OAuth2 PKCE ([#342](url))\n\n### Fixed\n\n- Token refresh race ([#341](url))\n',
    summaryPreview: {
        version: '1.5.0',
        date: 'May 18, 2026',
        headline: 'You can now sign in with OAuth2 PKCE.',
        body: 'This release adds secure OAuth2 PKCE login and fixes a token-refresh race on mobile.',
        highlights: ['Sign in with OAuth2 PKCE', 'Fixed token refresh race on mobile'],
        rawMarkdown:
            "## What's new in v1.5.0 · May 18, 2026\n\nYou can now sign in with OAuth2 PKCE.\n\nThis release adds secure OAuth2 PKCE login and fixes a token-refresh race on mobile.\n\n- Sign in with OAuth2 PKCE\n- Fixed token refresh race on mobile",
    },
    isMonorepo: false,
    monorepoInfo: null,
    packages: [],
    versioningScheme: 'semver',
    generatedAt: '2026-05-18T12:00:00Z',
};

describe('reportComment', () => {
    it('matches the PLAN.md §16 shape', () => {
        const md = reportComment(sampleReport);

        // Header / metadata
        expect(md).toContain('## Release report — generated by Tagline');
        expect(md).toContain('**Since:** `v1.4.2`');
        expect(md).toContain('**Branch:** `main`');
        expect(md).toContain('**PRs analyzed:** 3');
        expect(md).toContain('**Contributors:** 2');

        // Sections by kind
        expect(md).toContain('### ✨ New features · suggests `minor` bump');
        expect(md).toContain('OAuth2 PKCE support');
        expect(md).toContain('### 🐛 Bug fixes');
        expect(md).toContain('token refresh race');
        expect(md).toContain('### 🔧 Chores & maintenance');
        expect(md).toContain('upgrade to Node 22');

        // Recommendation + reasoning
        expect(md).toContain('**Suggested bump:** `minor` → `v1.5.0`');
        expect(md).toContain('> Two substantial new features');

        // Tickets are surfaced inline.
        expect(md).toContain('`PROJ-1201`');

        // Slash-command footer.
        expect(md).toContain('/approve patch');

        // Plain-language summary section (PLAN_ADDENDUM §6) — always rendered.
        expect(md).toContain('Plain-language summary');
        expect(md).toContain('You can now sign in with OAuth2 PKCE.');
        expect(md).toContain('- Sign in with OAuth2 PKCE');
        // The summary lives ABOVE the slash-command footer, not below.
        const summaryIdx = md.indexOf('Plain-language summary');
        const footerIdx = md.indexOf('Reply with a command');
        expect(summaryIdx).toBeLessThan(footerIdx);
    });

    it('omits empty sections', () => {
        const onlyFix: ReleaseReport = {
            ...sampleReport,
            prs: [sampleReport.prs[1]!],
            suggestedBump: 'patch',
            suggestedVersion: '1.4.3',
        };
        const md = reportComment(onlyFix);
        expect(md).not.toContain('### ✨ New features');
        expect(md).toContain('### 🐛 Bug fixes');
        expect(md).not.toContain('### 🔧 Chores');
    });

    it('handles first-release case with no prior tag', () => {
        const firstRelease: ReleaseReport = {
            ...sampleReport,
            lastTag: null,
            lastTagDate: null,
            suggestedVersion: '0.1.0',
        };
        const md = reportComment(firstRelease);
        expect(md).toContain('_first release_');
        expect(md).toContain('`v0.1.0`');
    });

    it('renders a per-package table for monorepo reports (M3)', () => {
        const monorepoReport: ReleaseReport = {
            ...sampleReport,
            isMonorepo: true,
            packages: [
                {
                    name: '@acme/api',
                    path: 'packages/api',
                    packageJsonPath: 'packages/api/package.json',
                    changelogPath: 'packages/api/CHANGELOG.md',
                    currentVersion: '1.0.0',
                    nextVersion: '1.1.0',
                    bumpType: 'minor',
                    prs: [sampleReport.prs[0]!],
                    changelogContent: '## [1.1.0]\n',
                    tagName: '@acme/api@1.1.0',
                },
                {
                    name: '@acme/ui',
                    path: 'packages/ui',
                    packageJsonPath: 'packages/ui/package.json',
                    changelogPath: 'packages/ui/CHANGELOG.md',
                    currentVersion: '0.5.0',
                    nextVersion: '0.5.1',
                    bumpType: 'patch',
                    prs: [sampleReport.prs[1]!],
                    changelogContent: '## [0.5.1]\n',
                    tagName: '@acme/ui@0.5.1',
                },
            ],
        };
        const md = reportComment(monorepoReport);
        expect(md).toContain('| Package |');
        expect(md).toContain('`@acme/api`');
        expect(md).toContain('`1.0.0 → 1.1.0`');
        expect(md).toContain('`@acme/ui`');
        expect(md).toContain('`0.5.0 → 0.5.1`');
        // Single-version "Suggested bump" line is suppressed.
        expect(md).not.toContain('**Suggested bump:**');
        // Footer advertises per-package grammar.
        expect(md).toContain('`/approve <name>:<bump>`');
        expect(md).not.toContain('/approve patch');
    });

    it('renders calver recommendation without bump wording', () => {
        const calverReport: ReleaseReport = {
            ...sampleReport,
            versioningScheme: 'calver',
            suggestedVersion: '2026.05.1',
            suggestedBump: 'minor', // advisory only — should not appear in the comment.
        };
        const md = reportComment(calverReport);
        expect(md).toContain('**Next version:** `v2026.05.1`');
        expect(md).toContain('_(scheme: calver)_');
        expect(md).not.toContain('Suggested bump:');
        // Footer should advertise `as <version>`, not bump words.
        expect(md).toContain('/approve as <version>');
        expect(md).not.toContain('/approve patch');
        // Features section drops the "suggests X bump" suffix.
        expect(md).toContain('### ✨ New features\n');
        expect(md).not.toContain('suggests `minor` bump');
    });
});

describe('acknowledgementComment', () => {
    it('uses different wording for report vs approve', () => {
        expect(acknowledgementComment('report')).toContain('generating');
        expect(acknowledgementComment('approve')).toContain('preparing');
    });
});

describe('noChangesComment', () => {
    it('mentions the last tag when present', () => {
        expect(noChangesComment('v1.0.0')).toContain('since `v1.0.0`');
    });
    it('handles first-release path', () => {
        expect(noChangesComment(null)).toContain('no merged PRs');
    });
});

describe('errorComment / noPermissionComment / missingWorkflowComment', () => {
    it('errorComment mentions the action', () => {
        expect(errorComment('generating the release report')).toContain('release report');
    });
    it('noPermissionComment @-mentions the user', () => {
        expect(noPermissionComment('alice')).toContain('@alice');
    });
    it('missingWorkflowComment includes a sample YAML', () => {
        expect(missingWorkflowComment()).toContain('workflow_dispatch');
    });
});

describe('defaultWorkflowYaml', () => {
    it('emits a workflow with both Phase A (workflow_dispatch) and Phase B (push) triggers', () => {
        const yaml = defaultWorkflowYaml();
        expect(yaml).toContain('workflow_dispatch:');
        expect(yaml).toContain('push:');
        expect(yaml).toContain('branches: [main, master]');
    });

    it('pins to the major-tag of the action', () => {
        // SemVer policy: examples and onboarding pin to `@v1` so users get
        // patch/minor updates inside the same major. Bare `@main` or
        // floating refs would silently land breaking changes.
        expect(defaultWorkflowYaml()).toContain('HelicanHQ/tagline-release-agent-action@v1');
    });

    it('grants the three required permissions and nothing else', () => {
        const yaml = defaultWorkflowYaml();
        expect(yaml).toContain('contents: write');
        expect(yaml).toContain('pull-requests: write');
        expect(yaml).toContain('issues: write');
        // No write to actions, deployments, packages, etc.
        expect(yaml).not.toMatch(/actions: write/);
        expect(yaml).not.toMatch(/deployments: write/);
    });

    it('is embedded verbatim in missingWorkflowComment (single source of truth)', () => {
        // If this fails, the two strings drifted — onboarding PR users and
        // recovery-path users would end up with subtly-different workflows.
        expect(missingWorkflowComment()).toContain(defaultWorkflowYaml());
    });
});
