import { describe, it, expect } from 'vitest';
import type { ReleaseReport } from '@tagline-sh/shared';
import {
    acknowledgementComment,
    errorComment,
    missingWorkflowComment,
    noChangesComment,
    noPermissionComment,
    reportComment,
    welcomeIssue,
} from '../../src/utils/comments.js';

const sampleReport: ReleaseReport = {
    repoOwner: 'acme',
    repoName: 'widget',
    baseBranch: 'main',
    lastTag: 'v1.4.2',
    lastTagDate: '2026-04-28T00:00:00Z',
    prs: [
        {
            number: 342,
            title: 'feat(api): OAuth2 PKCE support',
            url: 'https://github.com/acme/widget/pull/342',
            author: 'octocat',
            mergedAt: '2026-05-10T10:00:00Z',
            commits: [
                {
                    type: 'feat',
                    scope: 'api',
                    subject: 'OAuth2 PKCE support',
                    body: null,
                    isBreaking: false,
                    sha: 'a',
                },
            ],
            tickets: ['PROJ-1201'],
            suggestedBump: 'minor',
            bodyExcerpt: null,
        },
        {
            number: 341,
            title: 'fix: token refresh race',
            url: 'https://github.com/acme/widget/pull/341',
            author: 'octocat',
            mergedAt: '2026-05-11T10:00:00Z',
            commits: [
                {
                    type: 'fix',
                    scope: null,
                    subject: 'token refresh race',
                    body: null,
                    isBreaking: false,
                    sha: 'b',
                },
            ],
            tickets: ['PROJ-1199'],
            suggestedBump: 'patch',
            bodyExcerpt: null,
        },
        {
            number: 340,
            title: 'chore: upgrade to Node 22',
            url: 'https://github.com/acme/widget/pull/340',
            author: 'octobot',
            mergedAt: '2026-05-12T10:00:00Z',
            commits: [
                {
                    type: 'chore',
                    scope: null,
                    subject: 'upgrade to Node 22',
                    body: null,
                    isBreaking: false,
                    sha: 'c',
                },
            ],
            tickets: [],
            suggestedBump: 'none',
            bodyExcerpt: null,
        },
    ],
    suggestedBump: 'minor',
    suggestedVersion: '1.5.0',
    currentVersion: '1.4.2',
    reasoning: 'Two substantial new features (#342) qualify this as a minor release.',
    changelogPreview:
        '## [1.5.0] - 2026-05-18\n\n### Added\n\n- OAuth2 PKCE ([#342](url))\n\n### Fixed\n\n- Token refresh race ([#341](url))\n',
    isMonorepo: false,
    monorepoInfo: null,
    generatedAt: '2026-05-18T12:00:00Z',
};

describe('reportComment', () => {
    it('matches the PLAN.md §16 shape', () => {
        const md = reportComment(sampleReport);

        // Header / metadata
        expect(md).toContain('## Release report — generated by Tagline');
        expect(md).toContain('**Since:** `v1.4.2`');
        expect(md).toContain('**Branch:** `main`');
        expect(md).toContain('**PRs analyzed:** 3');
        expect(md).toContain('**Contributors:** 2');

        // Sections by kind
        expect(md).toContain('### ✨ New features · suggests `minor` bump');
        expect(md).toContain('OAuth2 PKCE support');
        expect(md).toContain('### 🐛 Bug fixes');
        expect(md).toContain('token refresh race');
        expect(md).toContain('### 🔧 Chores & maintenance');
        expect(md).toContain('upgrade to Node 22');

        // Recommendation + reasoning
        expect(md).toContain('**Suggested bump:** `minor` → `v1.5.0`');
        expect(md).toContain('> Two substantial new features');

        // Tickets are surfaced inline.
        expect(md).toContain('`PROJ-1201`');

        // Slash-command footer.
        expect(md).toContain('/approve patch');
    });

    it('omits empty sections', () => {
        const onlyFix: ReleaseReport = {
            ...sampleReport,
            prs: [sampleReport.prs[1]!],
            suggestedBump: 'patch',
            suggestedVersion: '1.4.3',
        };
        const md = reportComment(onlyFix);
        expect(md).not.toContain('### ✨ New features');
        expect(md).toContain('### 🐛 Bug fixes');
        expect(md).not.toContain('### 🔧 Chores');
    });

    it('handles first-release case with no prior tag', () => {
        const firstRelease: ReleaseReport = {
            ...sampleReport,
            lastTag: null,
            lastTagDate: null,
            suggestedVersion: '0.1.0',
        };
        const md = reportComment(firstRelease);
        expect(md).toContain('_first release_');
        expect(md).toContain('`v0.1.0`');
    });
});

describe('acknowledgementComment', () => {
    it('uses different wording for report vs approve', () => {
        expect(acknowledgementComment('report')).toContain('generating');
        expect(acknowledgementComment('approve')).toContain('preparing');
    });
});

describe('noChangesComment', () => {
    it('mentions the last tag when present', () => {
        expect(noChangesComment('v1.0.0')).toContain('since `v1.0.0`');
    });
    it('handles first-release path', () => {
        expect(noChangesComment(null)).toContain('no merged PRs');
    });
});

describe('errorComment / noPermissionComment / missingWorkflowComment', () => {
    it('errorComment mentions the action', () => {
        expect(errorComment('generating the release report')).toContain('release report');
    });
    it('noPermissionComment @-mentions the user', () => {
        expect(noPermissionComment('alice')).toContain('@alice');
    });
    it('missingWorkflowComment includes a sample YAML', () => {
        expect(missingWorkflowComment()).toContain('workflow_dispatch');
    });
});

describe('welcomeIssue', () => {
    it('has a welcoming title and a setup checklist', () => {
        const { title, body } = welcomeIssue();
        expect(title).toContain('Tagline');
        expect(body).toContain('- [ ] Add `.github/workflows/release-agent.yml`');
        expect(body).toContain('- [ ] Set `AI_API_KEY`');
        expect(body).toContain('/release-report');
    });
});
