import {
    APP_DISPLAY_NAME,
    type BumpType,
    type ParsedPR,
    type ReleaseReport,
} from '@tagline-sh/shared';

// All comment Markdown the bot posts is centralized here. Tests snapshot
// against these builders to catch accidental UX drift.

/** Posted immediately after `/release-report` so the user knows the bot is alive. */
export function acknowledgementComment(action: 'report' | 'approve'): string {
    if (action === 'report') {
        return `${APP_DISPLAY_NAME} is generating your release report — one moment…`;
    }
    return `${APP_DISPLAY_NAME} is preparing your release — one moment…`;
}

const SECTION_HEADERS: Record<'feat' | 'fix' | 'chore', string> = {
    feat: '### ✨ New features',
    fix: '### 🐛 Bug fixes',
    chore: '### 🔧 Chores & maintenance',
};

function ticketSuffix(pr: ParsedPR): string {
    if (pr.tickets.length === 0) return '';
    return ' · ' + pr.tickets.map((t) => `\`${t}\``).join(' ');
}

function prLine(pr: ParsedPR): string {
    return `- ${pr.title} · [#${pr.number}](${pr.url})${ticketSuffix(pr)}`;
}

function groupPRs(prs: ParsedPR[]): Record<'feat' | 'fix' | 'chore', ParsedPR[]> {
    const groups: Record<'feat' | 'fix' | 'chore', ParsedPR[]> = {
        feat: [],
        fix: [],
        chore: [],
    };
    for (const pr of prs) {
        if (pr.commits.some((c) => c.type === 'feat' || c.isBreaking)) {
            groups.feat.push(pr);
        } else if (pr.commits.some((c) => c.type === 'fix' || c.type === 'perf')) {
            groups.fix.push(pr);
        } else {
            groups.chore.push(pr);
        }
    }
    return groups;
}

function uniqueAuthors(prs: ParsedPR[]): number {
    return new Set(prs.map((pr) => pr.author)).size;
}

function totalCommits(prs: ParsedPR[]): number {
    return prs.reduce((acc, pr) => acc + pr.commits.length, 0);
}

const BUMP_LABELS: Record<BumpType, string> = {
    major: 'major',
    minor: 'minor',
    patch: 'patch',
    none: 'none',
};

function formatSince(report: ReleaseReport): string {
    if (!report.lastTag) return '_first release_';
    const date = report.lastTagDate ? new Date(report.lastTagDate) : null;
    if (!date || Number.isNaN(date.getTime())) return `\`${report.lastTag}\``;
    const formatted = date.toUTCString().slice(5, 16); // "DD Mon YYYY"
    return `\`${report.lastTag}\` · ${formatted}`;
}

/**
 * Render the full release report comment per PLAN.md §16. This is the comment
 * the bot edits its acknowledgement into once the report is ready.
 */
export function reportComment(report: ReleaseReport): string {
    const groups = groupPRs(report.prs);
    const bumpHint = BUMP_LABELS[report.suggestedBump];

    const lines: string[] = [];
    lines.push(`## Release report — generated by ${APP_DISPLAY_NAME}`);
    lines.push('');
    lines.push(
        `**Since:** ${formatSince(report)} &nbsp;|&nbsp; **Branch:** \`${report.baseBranch}\``,
    );
    lines.push(
        `**PRs analyzed:** ${report.prs.length} &nbsp;|&nbsp; **Commits:** ${totalCommits(
            report.prs,
        )} &nbsp;|&nbsp; **Contributors:** ${uniqueAuthors(report.prs)}`,
    );
    lines.push('');
    lines.push('---');

    if (groups.feat.length > 0) {
        lines.push('');
        // The "suggests X bump" hint only carries meaning for semver — calver
        // and incremental compute the version mechanically.
        const suffix =
            report.versioningScheme === 'semver' ? ` · suggests \`${bumpHint}\` bump` : '';
        lines.push(`${SECTION_HEADERS.feat}${suffix}`);
        lines.push('');
        for (const pr of groups.feat) lines.push(prLine(pr));
    }
    if (groups.fix.length > 0) {
        lines.push('');
        lines.push(SECTION_HEADERS.fix);
        lines.push('');
        for (const pr of groups.fix) lines.push(prLine(pr));
    }
    if (groups.chore.length > 0) {
        lines.push('');
        lines.push(SECTION_HEADERS.chore);
        lines.push('');
        for (const pr of groups.chore) lines.push(prLine(pr));
    }

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('### Recommendation');
    lines.push('');
    if (report.packages.length > 0) {
        // Monorepo (M3): per-package table replaces the single-version line.
        // Each row is what the action will ship; packages with no PRs since
        // the last tag are absent by design (won't be bumped).
        lines.push(
            `This release event ships **${report.packages.length} package${report.packages.length === 1 ? '' : 's'}**:`,
        );
        lines.push('');
        lines.push('| Package | Current → Next | Bump | PRs |');
        lines.push('|---|---|---|---|');
        for (const pkg of report.packages) {
            const prRefs = pkg.prs.map((p) => `#${p.number}`).join(', ') || '—';
            // The Bump column only carries meaning for semver. For calver /
            // incremental the version is mechanical, so we show the scheme name
            // instead of a `bumpType` category that doesn't apply (matches the
            // worked example in docs/monorepo.md).
            const bumpCell =
                report.versioningScheme === 'semver'
                    ? `\`${pkg.bumpType}\``
                    : `(${report.versioningScheme})`;
            lines.push(
                `| \`${pkg.name}\` | \`${pkg.currentVersion} → ${pkg.nextVersion}\` | ${bumpCell} | ${prRefs} |`,
            );
        }
        lines.push('');
        lines.push('_Packages without attributed PRs are skipped._');
    } else if (report.versioningScheme === 'semver') {
        lines.push(`**Suggested bump:** \`${bumpHint}\` → \`v${report.suggestedVersion}\``);
    } else {
        lines.push(
            `**Next version:** \`v${report.suggestedVersion}\` ` +
                `_(scheme: ${report.versioningScheme})_`,
        );
    }
    lines.push('');
    for (const line of report.reasoning.split('\n')) lines.push(`> ${line}`);

    lines.push('');
    lines.push('<details>');
    lines.push(
        '<summary>New changelog entry — will be prepended to <code>CHANGELOG.md</code> on release</summary>',
    );
    lines.push('');
    lines.push('```markdown');
    lines.push(report.changelogPreview.trimEnd());
    lines.push('```');
    lines.push('');
    lines.push('</details>');

    // Plain-language summary block — the user-facing release notes (PLAN_ADDENDUM
    // §6). Always rendered, even on the deterministic-fallback path; the
    // collapsible `<details>` keeps it out of the way when minimal, and a
    // consistent UI is easier to learn than one that conditionally appears.
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Plain-language summary (for Slack / product changelog)</summary>');
    lines.push('');
    lines.push(report.summaryPreview.rawMarkdown.trimEnd());
    lines.push('');
    lines.push('</details>');

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('Reply with a command to release:');
    lines.push(approveCommandHints(report));

    return lines.join('\n');
}

/**
 * Render the inline `/approve` quick-pick suggestions at the bottom of the
 * report comment. SemVer offers bump words; calver / incremental offer the
 * `as <version>` override instead because bump words are rejected. Monorepos
 * offer the per-package override grammar.
 */
function approveCommandHints(report: ReleaseReport): string {
    const flags = '`/approve --draft` &nbsp; `/approve --dry-run`';
    if (report.packages.length > 0) {
        return (
            '`/approve` &nbsp; `/approve <name>:<bump>` (e.g. `/approve api:minor ui:patch`) &nbsp; ' +
            flags
        );
    }
    if (report.versioningScheme === 'semver') {
        return (
            '`/approve` &nbsp; `/approve patch` &nbsp; `/approve minor` &nbsp; ' +
            '`/approve major` &nbsp; ' +
            flags
        );
    }
    return '`/approve` &nbsp; `/approve as <version>` &nbsp; ' + flags;
}

/** No-PRs-since-last-tag message. */
export function noChangesComment(lastTag: string | null): string {
    if (!lastTag) {
        return `${APP_DISPLAY_NAME}: no merged PRs detected. Nothing to release yet.`;
    }
    return `${APP_DISPLAY_NAME}: no changes detected since \`${lastTag}\`.`;
}

/**
 * Posted on the release-tracking issue when `/approve` is invoked while a
 * release PR for the same version already exists. The bot refuses to
 * dispatch a second workflow run; users need to merge or close the existing
 * PR first. This is intentionally a polite refusal rather than auto-
 * overwriting the existing PR — silently force-pushing over a PR the
 * reviewer is mid-way through merging would be a footgun.
 */
export function releasePRAlreadyOpenComment(args: {
    prNumber: number;
    prUrl: string;
    branch: string;
}): string {
    return [
        `${APP_DISPLAY_NAME}: a release PR is already open for this version, so I won't dispatch another one.`,
        '',
        `→ **PR #${args.prNumber}** — ${args.prUrl}`,
        `→ branch: \`${args.branch}\``,
        '',
        'Merge or close that PR before re-approving. To ship a different version, ' +
            'close the existing PR and run `/approve as X.Y.Z` to override.',
    ].join('\n');
}

/**
 * Canonical workflow YAML the user must drop into
 * `.github/workflows/release-agent.yml`. Exported so the onboarding PR body
 * and the missing-workflow fallback comment both pull from the same source.
 */
export function defaultWorkflowYaml(): string {
    return [
        'name: Release Agent',
        'on:',
        '  # Phase A — propose: opens a release PR with version bump + CHANGELOG.',
        '  # No tag or GitHub Release is created here.',
        '  workflow_dispatch:',
        '    inputs:',
        '      release_plan:',
        '        required: true',
        '        type: string',
        '      issue_number:',
        '        required: false',
        '        type: string',
        '        default: ""',
        '      dry_run:',
        '        required: false',
        '        type: boolean',
        '        default: false',
        '  # Phase B — finalize: tags the merge commit + publishes the GitHub',
        '  # Release once a release PR merges into a release-channel branch.',
        '  # Triggered on `push` because PRs opened with GITHUB_TOKEN do NOT fire',
        '  # `pull_request: closed` events (GitHub anti-recursion behavior). The',
        '  # action self-filters and no-ops for non-release pushes.',
        '  push:',
        '    # List every release-channel branch from your .release-agent.md here',
        '    # (e.g. staging, develop) so alpha/rc releases that merge into them',
        '    # also get tagged + published. Stable channel only by default:',
        '    branches: [main, master]',
        'jobs:',
        '  release:',
        "    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}",
        '    runs-on: ubuntu-latest',
        '    permissions:',
        '      contents: write',
        '      pull-requests: write',
        '      issues: write',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '        with: { fetch-depth: 0 }',
        '      - uses: HelicanHQ/tagline-release-agent-action@v1',
        '        with:',
        '          release_plan: ${{ inputs.release_plan }}',
        '          github_token: ${{ secrets.GITHUB_TOKEN }}',
        '          issue_number: ${{ inputs.issue_number }}',
        '          dry_run: ${{ inputs.dry_run }}',
    ].join('\n');
}

/**
 * Setup instructions when `.github/workflows/release-agent.yml` is missing.
 * `branch` names the release target — GitHub validates the `workflow_dispatch`
 * trigger on the dispatched branch, so the workflow must exist THERE, not just
 * on the default branch (the usual gotcha when a channel branch like `main`
 * lags the trunk where Tagline was first set up).
 */
export function missingWorkflowComment(branch?: string): string {
    const onBranch = branch ? ` on \`${branch}\`` : '';
    const intro = branch
        ? `This release targets the \`${branch}\` branch, and GitHub requires the workflow to ` +
          `exist on that branch (it validates the \`workflow_dispatch\` trigger there). Add this ` +
          `file to \`${branch}\` — e.g. by merging it from your default branch:`
        : 'Add this file to your repo:';
    return [
        `${APP_DISPLAY_NAME} can't trigger the release because \`.github/workflows/release-agent.yml\` is missing${onBranch}.`,
        '',
        intro,
        '',
        '```yaml',
        defaultWorkflowYaml(),
        '```',
    ].join('\n');
}

/** No-permission comment. */
export function noPermissionComment(username: string): string {
    return `@${username}, you need write access to this repository to use ${APP_DISPLAY_NAME} commands.`;
}

/** Generic error comment shown when something unexpected blows up. */
export function errorComment(action: string, detail?: string): string {
    const base = `${APP_DISPLAY_NAME} hit an error while ${action}.`;
    if (detail && detail.trim().length > 0) {
        // Detail is shown verbatim so users get actionable info (e.g. "release
        // plan is N bytes, exceeds the workflow_dispatch input limit"). Keep
        // it surrounded by blockquote markers so it visually separates from
        // the canned wrapper.
        return `${base}\n\n> ${detail.trim().split('\n').join('\n> ')}\n\nIf this keeps happening, check the bot logs or open an issue.`;
    }
    return `${base} Please try again, or check the bot logs.`;
}
