import {
    APP_DISPLAY_NAME,
    type BumpType,
    type ParsedPR,
    type ReleaseReport,
} from '@tagline-sh/shared';

// All comment Markdown the bot posts is centralized here. Tests snapshot
// against these builders to catch accidental UX drift.

/** Posted immediately after `/release-report` so the user knows the bot is alive. */
export function acknowledgementComment(action: 'report' | 'approve'): string {
    if (action === 'report') {
        return `${APP_DISPLAY_NAME} is generating your release report — one moment…`;
    }
    return `${APP_DISPLAY_NAME} is preparing your release — one moment…`;
}

const SECTION_HEADERS: Record<'feat' | 'fix' | 'chore', string> = {
    feat: '### ✨ New features',
    fix: '### 🐛 Bug fixes',
    chore: '### 🔧 Chores & maintenance',
};

function ticketSuffix(pr: ParsedPR): string {
    if (pr.tickets.length === 0) return '';
    return ' · ' + pr.tickets.map((t) => `\`${t}\``).join(' ');
}

function prLine(pr: ParsedPR): string {
    return `- ${pr.title} · [#${pr.number}](${pr.url})${ticketSuffix(pr)}`;
}

function groupPRs(prs: ParsedPR[]): Record<'feat' | 'fix' | 'chore', ParsedPR[]> {
    const groups: Record<'feat' | 'fix' | 'chore', ParsedPR[]> = {
        feat: [],
        fix: [],
        chore: [],
    };
    for (const pr of prs) {
        if (pr.commits.some((c) => c.type === 'feat' || c.isBreaking)) {
            groups.feat.push(pr);
        } else if (pr.commits.some((c) => c.type === 'fix' || c.type === 'perf')) {
            groups.fix.push(pr);
        } else {
            groups.chore.push(pr);
        }
    }
    return groups;
}

function uniqueAuthors(prs: ParsedPR[]): number {
    return new Set(prs.map((pr) => pr.author)).size;
}

function totalCommits(prs: ParsedPR[]): number {
    return prs.reduce((acc, pr) => acc + pr.commits.length, 0);
}

const BUMP_LABELS: Record<BumpType, string> = {
    major: 'major',
    minor: 'minor',
    patch: 'patch',
    none: 'none',
};

function formatSince(report: ReleaseReport): string {
    if (!report.lastTag) return '_first release_';
    const date = report.lastTagDate ? new Date(report.lastTagDate) : null;
    if (!date || Number.isNaN(date.getTime())) return `\`${report.lastTag}\``;
    const formatted = date.toUTCString().slice(5, 16); // "DD Mon YYYY"
    return `\`${report.lastTag}\` · ${formatted}`;
}

/**
 * Render the full release report comment per PLAN.md §16. This is the comment
 * the bot edits its acknowledgement into once the report is ready.
 */
export function reportComment(report: ReleaseReport): string {
    const groups = groupPRs(report.prs);
    const bumpHint = BUMP_LABELS[report.suggestedBump];

    const lines: string[] = [];
    lines.push(`## Release report — generated by ${APP_DISPLAY_NAME}`);
    lines.push('');
    lines.push(
        `**Since:** ${formatSince(report)} &nbsp;|&nbsp; **Branch:** \`${report.baseBranch}\``,
    );
    lines.push(
        `**PRs analyzed:** ${report.prs.length} &nbsp;|&nbsp; **Commits:** ${totalCommits(
            report.prs,
        )} &nbsp;|&nbsp; **Contributors:** ${uniqueAuthors(report.prs)}`,
    );
    lines.push('');
    lines.push('---');

    if (groups.feat.length > 0) {
        lines.push('');
        // The "suggests X bump" hint only carries meaning for semver — calver
        // and incremental compute the version mechanically.
        const suffix =
            report.versioningScheme === 'semver' ? ` · suggests \`${bumpHint}\` bump` : '';
        lines.push(`${SECTION_HEADERS.feat}${suffix}`);
        lines.push('');
        for (const pr of groups.feat) lines.push(prLine(pr));
    }
    if (groups.fix.length > 0) {
        lines.push('');
        lines.push(SECTION_HEADERS.fix);
        lines.push('');
        for (const pr of groups.fix) lines.push(prLine(pr));
    }
    if (groups.chore.length > 0) {
        lines.push('');
        lines.push(SECTION_HEADERS.chore);
        lines.push('');
        for (const pr of groups.chore) lines.push(prLine(pr));
    }

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('### Recommendation');
    lines.push('');
    if (report.packages.length > 0) {
        // Monorepo (M3): per-package table replaces the single-version line.
        // Each row is what the action will ship; packages with no PRs since
        // the last tag are absent by design (won't be bumped).
        lines.push(
            `This release event ships **${report.packages.length} package${report.packages.length === 1 ? '' : 's'}**:`,
        );
        lines.push('');
        lines.push('| Package | Current → Next | Bump | PRs |');
        lines.push('|---|---|---|---|');
        for (const pkg of report.packages) {
            const prRefs = pkg.prs.map((p) => `#${p.number}`).join(', ') || '—';
            lines.push(
                `| \`${pkg.name}\` | \`${pkg.currentVersion} → ${pkg.nextVersion}\` | \`${pkg.bumpType}\` | ${prRefs} |`,
            );
        }
        lines.push('');
        lines.push('_Packages without attributed PRs are skipped._');
    } else if (report.versioningScheme === 'semver') {
        lines.push(`**Suggested bump:** \`${bumpHint}\` → \`v${report.suggestedVersion}\``);
    } else {
        lines.push(
            `**Next version:** \`v${report.suggestedVersion}\` ` +
                `_(scheme: ${report.versioningScheme})_`,
        );
    }
    lines.push('');
    for (const line of report.reasoning.split('\n')) lines.push(`> ${line}`);

    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Changelog preview</summary>');
    lines.push('');
    lines.push('```markdown');
    lines.push(report.changelogPreview.trimEnd());
    lines.push('```');
    lines.push('');
    lines.push('</details>');

    // Plain-language summary block — the user-facing release notes (PLAN_ADDENDUM
    // §6). Always rendered, even on the deterministic-fallback path; the
    // collapsible `<details>` keeps it out of the way when minimal, and a
    // consistent UI is easier to learn than one that conditionally appears.
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Plain-language summary (for Slack / product changelog)</summary>');
    lines.push('');
    lines.push(report.summaryPreview.rawMarkdown.trimEnd());
    lines.push('');
    lines.push('</details>');

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('Reply with a command to release:');
    lines.push(approveCommandHints(report));

    return lines.join('\n');
}

/**
 * Render the inline `/approve` quick-pick suggestions at the bottom of the
 * report comment. SemVer offers bump words; calver / incremental offer the
 * `as <version>` override instead because bump words are rejected. Monorepos
 * offer the per-package override grammar.
 */
function approveCommandHints(report: ReleaseReport): string {
    const flags = '`/approve --draft` &nbsp; `/approve --dry-run`';
    if (report.packages.length > 0) {
        return (
            '`/approve` &nbsp; `/approve <name>:<bump>` (e.g. `/approve api:minor ui:patch`) &nbsp; ' +
            flags
        );
    }
    if (report.versioningScheme === 'semver') {
        return (
            '`/approve` &nbsp; `/approve patch` &nbsp; `/approve minor` &nbsp; ' +
            '`/approve major` &nbsp; ' +
            flags
        );
    }
    return '`/approve` &nbsp; `/approve as <version>` &nbsp; ' + flags;
}

/** No-PRs-since-last-tag message. */
export function noChangesComment(lastTag: string | null): string {
    if (!lastTag) {
        return `${APP_DISPLAY_NAME}: no merged PRs detected. Nothing to release yet.`;
    }
    return `${APP_DISPLAY_NAME}: no changes detected since \`${lastTag}\`.`;
}

/** Setup instructions when `.github/workflows/release-agent.yml` is missing. */
export function missingWorkflowComment(): string {
    return [
        `${APP_DISPLAY_NAME} can't trigger the release because \`.github/workflows/release-agent.yml\` is missing.`,
        '',
        'Add this file to your repo:',
        '',
        '```yaml',
        'name: Release Agent',
        'on:',
        '  # Phase A — propose: opens a release PR with version bump + CHANGELOG.',
        '  # No tag or GitHub Release is created here.',
        '  workflow_dispatch:',
        '    inputs:',
        '      release_plan:',
        '        required: true',
        '        type: string',
        '      issue_number:',
        '        required: false',
        '        type: string',
        '        default: ""',
        '      dry_run:',
        '        required: false',
        '        type: boolean',
        '        default: false',
        '  # Phase B — finalize: tags the merge commit + publishes the GitHub',
        '  # Release once the release PR is merged into the production branch.',
        '  # Triggered on `push` because PRs opened with GITHUB_TOKEN do NOT fire',
        '  # `pull_request: closed` events (GitHub anti-recursion behavior). The',
        '  # action self-filters and no-ops for non-release pushes.',
        '  push:',
        '    branches: [main, master]',
        'jobs:',
        '  release:',
        "    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}",
        '    runs-on: ubuntu-latest',
        '    permissions:',
        '      contents: write',
        '      pull-requests: write',
        '      issues: write',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '        with: { fetch-depth: 0 }',
        '      - uses: tagline-sh/release-agent-action@v1',
        '        with:',
        '          release_plan: ${{ inputs.release_plan }}',
        '          github_token: ${{ secrets.GITHUB_TOKEN }}',
        '          issue_number: ${{ inputs.issue_number }}',
        '          dry_run: ${{ inputs.dry_run }}',
        '```',
    ].join('\n');
}

/** No-permission comment. */
export function noPermissionComment(username: string): string {
    return `@${username}, you need write access to this repository to use ${APP_DISPLAY_NAME} commands.`;
}

/** Generic error comment shown when something unexpected blows up. */
export function errorComment(action: string, detail?: string): string {
    const base = `${APP_DISPLAY_NAME} hit an error while ${action}.`;
    if (detail && detail.trim().length > 0) {
        // Detail is shown verbatim so users get actionable info (e.g. "release
        // plan is N bytes, exceeds the workflow_dispatch input limit"). Keep
        // it surrounded by blockquote markers so it visually separates from
        // the canned wrapper.
        return `${base}\n\n> ${detail.trim().split('\n').join('\n> ')}\n\nIf this keeps happening, check the bot logs or open an issue.`;
    }
    return `${base} Please try again, or check the bot logs.`;
}

/** Issue body posted when the GitHub App is first installed. */
export function welcomeIssue(): { title: string; body: string } {
    return {
        title: `👋 Welcome to ${APP_DISPLAY_NAME}`,
        body: [
            `Thanks for installing **${APP_DISPLAY_NAME}**!`,
            '',
            "Here's what to do next:",
            '',
            '- [ ] Add `.github/workflows/release-agent.yml` to your repo (see the docs).',
            '- [ ] Set `AI_API_KEY` in your repo secrets (any OpenAI-compatible provider).',
            `- [ ] Optionally add \`.release-agent.md\` to configure ${APP_DISPLAY_NAME}.`,
            '',
            '## How the release flow works',
            '',
            `Once setup is complete, ${APP_DISPLAY_NAME} watches PRs merged into your production branch. When the first PR after a release lands, it opens a **release-tracking issue** labeled \`tagline:release-pending\` and keeps it up to date as more PRs merge.`,
            '',
            'That issue is the only place slash commands work. Comment `/release-report` there to preview the release, then `/approve` to ship.',
            '',
            'Comments on any other issue or PR are ignored — this keeps the bot quiet on unrelated conversations.',
            '',
            `Questions? See the [docs](https://github.com/tagline-sh/tagline-sh).`,
        ].join('\n'),
    };
}
